# Generated by Django 6.0.1 on 2026-02-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otp_rename_is_admin_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='default_user', max_length=100),
            preserve_default=False,
        ),
    ]
