# Generated by Django 6.0.1 on 2026-02-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_verified'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='otp',
            unique_together={('phone', 'otp')},
        ),
    ]
