# Generated by Django 4.2.7 on 2026-03-20 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=100)),
                ('farm_code', models.CharField(blank=True, max_length=30, unique=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_unit', models.CharField(choices=[('acre', 'Acre'), ('hectare', 'Hectare')], default='acre', max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('crop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sowing_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('farmer', 'farm_name')},
            },
        ),
    ]
