export const tipsMockData = {

  "Yield Optimization": [
    " Use certified high-quality seeds",
    " Maintain proper spacing between crops",
    " Practice crop rotation",
    " Use organic fertilizers regularly",
    " Test soil before planting",
    " Maintain proper soil pH",
    " Ensure adequate sunlight exposure",
    " Avoid waterlogging in fields",
    " Control weeds regularly",
    " Monitor crop growth weekly",
    " Use modern farming equipment",
    " Follow recommended sowing time",
    " Apply fertilizers in correct quantity",
    " Use hybrid seeds for better yield",
    " Protect crops from extreme weather",
    " Harvest crops at right time",
    " Use mulching to retain moisture",
    " Improve soil health with compost",
    " Use bio-fertilizers",
    " Follow government farming guidelines",
    " Improve irrigation planning",
    " Maintain field records",
    " Use crop insurance",
    " Monitor pests early",
    " Improve drainage system",
    " Adopt smart farming tools",
    " Use AI-based predictions",
    " Follow seasonal cropping",
    " Optimize fertilizer timing",
    " Maintain soil nutrients",
    " Avoid over-ploughing",
    " Encourage biodiversity",
    " Protect soil from erosion",
    " Use organic pesticides",
    " Track yield data",
    " Use mobile farming apps",
    " Consult agriculture experts",
    " Upgrade irrigation systems",
    " Avoid monocropping",
    " Improve harvesting methods"
  ],

  "Irrigation Tips": [
    " Water crops early morning or evening",
    "Avoid over-irrigation",
    " Use drip irrigation systems",
    " Check soil moisture before watering",
    " Install proper drainage system",
    " Use sprinkler irrigation for large areas",
    " Conserve rainwater",
    " Avoid waterlogging",
    " Irrigate more during flowering stage",
    " Reduce irrigation during rainy season",
    " Use mulching to retain moisture",
    " Monitor weather forecast regularly",
    " Use canal water efficiently",
    " Repair leakage in irrigation pipes",
    " Avoid irrigation during peak sunlight",
    " Maintain uniform water distribution",
    " Use sensors if available",
    " Irrigate according to crop type",
    " Avoid flood irrigation methods",
    " Use groundwater responsibly",
    " Use automated irrigation",
    " Track water usage",
    " Avoid soil erosion",
    " Maintain irrigation schedule",
    " Use water-saving techniques",
    " Build rainwater harvesting system",
    " Monitor humidity levels",
    " Avoid uneven watering",
    " Use smart irrigation apps",
    " Improve water retention",
    " Protect irrigation channels",
    " Use solar pumps",
    " Maintain water quality",
    " Avoid contamination",
    " Use proper irrigation tools",
    " Train workers for irrigation",
    " Check pipe pressure regularly",
    " Avoid water wastage",
    " Upgrade irrigation methods",
    " Maintain irrigation logs"
  ],

  "Fertilizer Tips": [
    " Test soil before applying fertilizers",
    " Use balanced NPK fertilizers",
    " Avoid overuse of chemical fertilizers",
    " Apply compost and organic manure",
    " Use bio-fertilizers",
    " Apply fertilizers in split doses",
    " Follow recommended dosage",
    " Apply near root zone",
    " Avoid applying in extreme heat",
    " Mix organic and chemical fertilizers",
    " Maintain soil pH balance",
    " Store fertilizers properly",
    " Use green manure crops",
    " Apply micronutrients if needed",
    " Avoid fertilizer wastage",
    " Use foliar spray when needed",
    " Avoid applying before heavy rain",
    " Follow crop-specific fertilizer plan",
    " Use eco-friendly fertilizers",
    " Improve soil fertility over time",
    " Use slow-release fertilizers",
    " Monitor nutrient deficiency",
    " Use precision farming tools",
    " Track fertilizer usage",
    " Improve soil microbes",
    " Avoid soil contamination",
    " Rotate fertilizer types",
    " Apply based on season",
    " Avoid excess nitrogen",
    " Use digital soil testing",
    " Improve organic matter",
    " Maintain fertilizer balance",
    " Reduce chemical dependency",
    " Use liquid fertilizers",
    " Follow safety precautions",
    " Improve fertilizer storage",
    " Avoid expired fertilizers",
    " Maintain application records",
    " Optimize fertilizer cost",
    " Improve crop nutrition planning"
  ],

  "Pest Alerts": [
    " Inspect crops regularly",
    "Use neem oil spray",
    " Remove infected plants immediately",
    " Use pheromone traps",
    " Avoid excessive pesticide usage",
    " Practice crop rotation",
    " Use pest-resistant seeds",
    " Maintain field hygiene",
    " Encourage natural predators",
    " Spray during morning or evening",
    " Identify pest before treatment",
    " Avoid spraying in windy weather",
    " Use organic pest control",
    " Monitor leaf damage signs",
    " Avoid chemical overuse",
    " Keep tools clean",
    " Use light traps for insects",
    " Follow proper spray dosage",
    " Wear safety gear while spraying",
    " Keep records of pest attacks",
    " Use AI pest detection",
    " Monitor pest cycles",
    " Avoid over spraying",
    " Improve field sanitation",
    " Use biological controls",
    " Track pest patterns",
    " Use smart traps",
    " Protect beneficial insects",
    " Avoid pesticide resistance",
    " Maintain spray equipment",
    " Use eco-friendly sprays",
    " Train workers for pest control",
    " Monitor weather impact",
    " Avoid contamination",
    " Maintain pest logs",
    " Improve early detection",
    " Follow integrated pest management",
    " Use digital pest monitoring",
    " Avoid unnecessary spraying",
    " Improve crop immunity"
  ]

};